### ISSUE TITLE
Converting TensorFlow model to Caffe2 model

### ISSUE THREAD

**Issue by lhCheung1991** [edgarriba/DeepRosetta#17]
Hi,

I am trying to convert TensorFlow model to Caffe2 model, I want to use the importer of TensorFlow of this project, may I have more detailed document about it.

Thx

**Comment by edgarriba** [comment]
@lhCheung1991 this project has not being updated from a while. You should first check that th tensorflow importer still works with the last tensorflow version. Any contribution is welcomed to port stuff to new frameworks.

**Comment by lhCheung1991** [comment]
@edgarriba Thx.
